// Shared names keep the picker, accessible labels, and server validation aligned.
export const REACTIONS = [
  ["👍", "thumbs up"],
  ["👎", "thumbs down"],
  ["❤️", "heart"],
  ["😂", "joy laugh"],
  ["🎉", "celebrate tada"],
  ["✅", "done check"],
  ["👀", "eyes looking"],
  ["🙌", "raised hands"],
  ["🔥", "fire"],
  ["👏", "clap"],
  ["🙏", "thanks pray"],
  ["💯", "hundred"],
  ["😊", "smile"],
  ["😀", "grin"],
  ["😅", "sweat smile"],
  ["🤣", "rolling laugh"],
  ["😍", "heart eyes"],
  ["🥰", "love"],
  ["😎", "cool sunglasses"],
  ["🤔", "thinking"],
  ["🤯", "mind blown"],
  ["😮", "surprised"],
  ["😢", "sad cry"],
  ["😭", "sob"],
  ["😬", "grimace"],
  ["😴", "sleep"],
  ["🤩", "star struck"],
  ["🥳", "party"],
  ["🫡", "salute"],
  ["🤝", "handshake"],
  ["💪", "muscle strong"],
  ["👋", "wave hello"],
  ["👌", "okay hand"],
  ["🤞", "fingers crossed"],
  ["✌️", "peace victory"],
  ["✋", "raised hand"],
  ["💚", "green heart"],
  ["💙", "blue heart"],
  ["💜", "purple heart"],
  ["💛", "yellow heart"],
  ["🚀", "rocket ship"],
  ["✨", "sparkles"],
  ["⭐", "star"],
  ["💡", "idea bulb"],
  ["🏆", "trophy win"],
  ["🎯", "target"],
  ["💻", "computer"],
  ["🐛", "bug"],
  ["🔧", "wrench fix"],
  ["📝", "note memo"],
  ["📌", "pin"],
  ["📣", "announcement"],
  ["❓", "question"],
  ["❗", "exclamation"],
  ["⚠️", "warning"],
  ["❌", "no cross"],
  ["⏳", "waiting hourglass"],
  ["🔍", "search"],
  ["☕", "coffee"],
  ["🍕", "pizza"],
  ["🎂", "birthday cake"],
  ["🌱", "seedling grow"],
  ["🌈", "rainbow"],
  ["🐶", "dog"],
] as const;
export const REACTION_NAMES = new Map<string, string>(REACTIONS);
