// M2 validation: feed a handwriting-style photo to the one-shot vision pipeline
// and confirm it transcribes + extracts structure. Requires Ollama running with
// qwen2.5vl:7b pulled, and /tmp/gymlog.png present (generated by the harness).
use base64::Engine;
use tauri_app_lib::pipeline;

#[tokio::test]
async fn reads_handwritten_photo() {
    let path = "/tmp/gymlog.png";
    if !std::path::Path::new(path).exists() {
        eprintln!("skip: {path} not present");
        return;
    }
    let bytes = std::fs::read(path).unwrap();
    let b64 = base64::engine::general_purpose::STANDARD.encode(&bytes);

    let p = pipeline::categorize_photo("(none yet)", &[], &b64, "2026-06-15")
        .await
        .expect("vision pipeline returns a proposal");

    let raw = p["raw_text"].as_str().unwrap_or("");
    let e = &p["entries"][0];
    println!("--- transcription ---\n{raw}");
    println!("--- category: {} ---", e["category"]);
    println!(
        "--- data ---\n{}",
        serde_json::to_string_pretty(&e["data"]).unwrap()
    );

    assert_eq!(e["is_new_category"], serde_json::json!(true));
    assert!(e["data"].is_object(), "data is an object");

    // The note is dated "6/2"; with today=2026-06-15 it must resolve to 2026-06-02.
    println!(
        "event_date: {} (extracted={})",
        p["event_date"], p["date_was_extracted"]
    );
    assert_eq!(
        p["event_date"],
        serde_json::json!("2026-06-02"),
        "reads the 6/2 date off the photo"
    );
    assert_eq!(p["date_was_extracted"], serde_json::json!(true));

    // The model should have read the workout off the image.
    let blob = format!(
        "{} {}",
        raw.to_lowercase(),
        e["data"].to_string().to_lowercase()
    );
    assert!(blob.contains("squat"), "should read 'squat'; got: {blob}");
    assert!(
        blob.contains("225"),
        "should read the 225 weight; got: {blob}"
    );
}
